experiment_name: 'big_prova' # IMPORTANT TO CHANGE!!!

total_timesteps: 3000000
device: 'cpu' # or 'cuda'

callback:
  early_stopping: True
  patience: 10
  delta: 0.05
  save_freq: 10
  tensorboard_path: 'saved_models/'

circuit:
  circuit:
    - 
      - [0, 1, 0, 0]
      - [1, 0, 0, 0]
      - [0, 0, 0, 1]
      - [0, 0, 1, 0]
  random_circuits: True
  n_slices: 12
  n_qbits: 4


levels:
  level1: [1]
  level2: [2]

action_type: 'L' # or L

weights_reward:
  nonlocal: 10
  intervention: 0
  direct_capacity_violation: 30
  missing_space_for_interaction_violation: 20
  no_space_for_future_gates_violation: 15

ppo:
  batch_size: 64
  learning_rate: 0.0005
  n_steps: 4096
  gae_lambda: 0.95


policy_kwargs:
  net_arch:
    pi: [64, 64]
    vf: [64, 64] # does not include the first layer
  features_extractor_kwargs:
    hidden_features: 64
    num_heads: 1
    hidden_layers: 4
    dropout: 0.3
    out_features: 16
    gnn_name: 'GATv2' # or 'GCN'
  