[project]
name = "drl-mapping"
version = "0.1.0"
description = ""
authors = [
    {name = "Sergi Tomàs"},
    {name = "Laia Mogas"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sparse (>=0.15.5,<0.16.0)",
    "torch (>=2.6.0,<3.0.0)",
    "stable-baselines3 (>=2.5.0,<3.0.0)",
    "sb3-contrib (>=2.5.0,<3.0.0)",
    "wandb (>=0.19.7,<0.20.0)",
    "torch-geometric (>=2.6.1,<3.0.0)",
    "tensorboard (>=2.19.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
